---
deployment:
  tasks:
    - export DEPLOYPATH=/home/athar/athargroup.com/productsourcing/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp product-sourcing-dashboard.css $DEPLOYPATH
    - /bin/cp product-sourcing-dashboard.js $DEPLOYPATH
